// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: svc/v1/testservice.proto

package svcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CapsRequest) Reset() {
	*x = CapsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_v1_testservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsRequest) ProtoMessage() {}

func (x *CapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_testservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsRequest.ProtoReflect.Descriptor instead.
func (*CapsRequest) Descriptor() ([]byte, []int) {
	return file_svc_v1_testservice_proto_rawDescGZIP(), []int{0}
}

func (x *CapsRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CapsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CapsResponse) Reset() {
	*x = CapsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_v1_testservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsResponse) ProtoMessage() {}

func (x *CapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_testservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsResponse.ProtoReflect.Descriptor instead.
func (*CapsResponse) Descriptor() ([]byte, []int) {
	return file_svc_v1_testservice_proto_rawDescGZIP(), []int{1}
}

func (x *CapsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MustErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg string `protobuf:"bytes,1,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *MustErrorRequest) Reset() {
	*x = MustErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_v1_testservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MustErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MustErrorRequest) ProtoMessage() {}

func (x *MustErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_testservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MustErrorRequest.ProtoReflect.Descriptor instead.
func (*MustErrorRequest) Descriptor() ([]byte, []int) {
	return file_svc_v1_testservice_proto_rawDescGZIP(), []int{2}
}

func (x *MustErrorRequest) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type MustErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MustErrorResponse) Reset() {
	*x = MustErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_v1_testservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MustErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MustErrorResponse) ProtoMessage() {}

func (x *MustErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_testservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MustErrorResponse.ProtoReflect.Descriptor instead.
func (*MustErrorResponse) Descriptor() ([]byte, []int) {
	return file_svc_v1_testservice_proto_rawDescGZIP(), []int{3}
}

var File_svc_v1_testservice_proto protoreflect.FileDescriptor

var file_svc_v1_testservice_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x76, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x76, 0x63, 0x2e,
	0x76, 0x31, 0x22, 0x1f, 0x0a, 0x0b, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x20, 0x0a, 0x0c, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2b, 0x0a, 0x10, 0x4d, 0x75, 0x73, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x75, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x70, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x43, 0x61, 0x70, 0x73, 0x12,
	0x13, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09,
	0x4d, 0x75, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x75, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x73,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x91, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x42,
	0x10, 0x54, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x61, 0x72, 0x61, 0x6b, 0x6d, 0x69, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x70, 0x79, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x76, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x76, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x53, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x53, 0x76, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x53,
	0x76, 0x63, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x12, 0x53, 0x76, 0x63, 0x5c, 0x56, 0x31, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x53, 0x76, 0x63,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_v1_testservice_proto_rawDescOnce sync.Once
	file_svc_v1_testservice_proto_rawDescData = file_svc_v1_testservice_proto_rawDesc
)

func file_svc_v1_testservice_proto_rawDescGZIP() []byte {
	file_svc_v1_testservice_proto_rawDescOnce.Do(func() {
		file_svc_v1_testservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_v1_testservice_proto_rawDescData)
	})
	return file_svc_v1_testservice_proto_rawDescData
}

var file_svc_v1_testservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_svc_v1_testservice_proto_goTypes = []interface{}{
	(*CapsRequest)(nil),       // 0: svc.v1.CapsRequest
	(*CapsResponse)(nil),      // 1: svc.v1.CapsResponse
	(*MustErrorRequest)(nil),  // 2: svc.v1.MustErrorRequest
	(*MustErrorResponse)(nil), // 3: svc.v1.MustErrorResponse
}
var file_svc_v1_testservice_proto_depIdxs = []int32{
	0, // 0: svc.v1.CapsService.Caps:input_type -> svc.v1.CapsRequest
	2, // 1: svc.v1.CapsService.MustError:input_type -> svc.v1.MustErrorRequest
	1, // 2: svc.v1.CapsService.Caps:output_type -> svc.v1.CapsResponse
	3, // 3: svc.v1.CapsService.MustError:output_type -> svc.v1.MustErrorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_v1_testservice_proto_init() }
func file_svc_v1_testservice_proto_init() {
	if File_svc_v1_testservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_v1_testservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_v1_testservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_v1_testservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MustErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_v1_testservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MustErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_v1_testservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_v1_testservice_proto_goTypes,
		DependencyIndexes: file_svc_v1_testservice_proto_depIdxs,
		MessageInfos:      file_svc_v1_testservice_proto_msgTypes,
	}.Build()
	File_svc_v1_testservice_proto = out.File
	file_svc_v1_testservice_proto_rawDesc = nil
	file_svc_v1_testservice_proto_goTypes = nil
	file_svc_v1_testservice_proto_depIdxs = nil
}
